### ISSUE TITLE
How much of Google's Progressive Web App Checklist have I completed?

### ISSUE THREAD

**Issue by geoffreyyip** [geoffreyyip/mta-dashboard#16]
See https://developers.google.com/web/progressive-web-apps/checklist.

**Comment by geoffreyyip** [comment]
### Is a Progressive Web App

- [ ] Registers a Service Worker
_The service worker is the technology that enables your app to use many Progressive Web App features, such as offline, add to homescreen, and push notifications._
- [ ] Responds with a 200 when offline
_If you're building a Progressive Web App, consider using a service worker so that your app can work offline_
- [ ] User can be prompted to Install the Web App
_Failures: No manifest was fetched, Site does not register a Service Worker, Manifest start\_url is not cached by a Service Worker._
- [ ] Configured for a custom splash screen
_Failures: No manifest was fetched._
- [ ] Address bar matches brand colors
_Failures: No manifest was fetched, No `<meta name="theme-color">` tag found._
- [ ] Page transitions don't feel like they block on the network
_Transitions should feel snappy as you tap around, even on a slow network, a key to perceived performance_
- [x] Contains some content when JavaScript is not available
- [x] Uses HTTPS
- [x] Redirects HTTP traffic to HTTPS
- [x] Page load is fast enough on 3G
- [x] Has a <meta name="viewport"> tag with width or initial-scale
- [x] Content is sized correctly for the viewport
- [x] Each page has a URL
- [x] Site works cross-browser

### Performance

- [x] First meaningful paint: 1,290 ms
- [x] First Interactive (beta): 1,430 ms
- [x] Consistently Interactive (beta): 1,430 ms
- [x] Low Estimated Input Latency: 16 ms (target: < 50 ms)
- [ ] Need to reduce render-blocking stylesheets
_/css/style.css estimated to delay paint by 533ms_
- [ ] Need to enable text compression
_Uncompressed resource URL / can be compressed from 6KB to 1KB with GZIP, a 5KB savings_

### Accessibility

100%

### Best Practices
- [ ] Uses HTTP/2 for its own resources: 2 requests were not handled over h2
_HTTP/2 offers many benefits over HTTP/1.1, including binary headers, multiplexing, and server push. Change / and /dashboard route._
- [ ] Manifest's short_name won't be truncated when displayed on homescreen
_Make your app's `short_name` less than 12 characters to ensure that it's not truncated on homescreens._
- [x] View 11 passed items
- [x] Avoids Application Cache
- [x] Avoids WebSQL DB
- [x] Uses HTTPS
- [x] Uses passive listeners to improve scrolling performance
- [x] Avoids Mutation Events in its own scripts
- [x] Avoids document.write()
- [x] Opens external anchors using rel="noopener"
- [x] Avoids requesting the geolocation permission on page load
- [x] Avoids requesting the notification permission on page load
- [x] Avoids deprecated APIs
- [x] Allows to paste into password input fields
